### ISSUE TITLE
Unable to read private key from .ini file

### ISSUE THREAD

**Issue by omkar1117** [docusign/eg-01-python-jwt#2]
I updated the config.ini file and tried to read the private key it is throwing error with config parser.

**Comment by LarryKlugerDS** [comment]
Hi,

I'm sorry that you're having this problem.
Did you add spaces as needed -- 

>Note: the private key's second and subsequent lines need to have a space added at the beginning due to requirements from the Python configuration file parser. See the example config file for an example.

Thanks,
Larry

**Comment by omkar1117** [comment]
@LarryKlugerDS yes

**Comment by LarryKlugerDS** [comment]
I have just done some refactoring and additional testing of the example. 
It is all working ok. Please re-open this issue if you are still having a problem. 

Thanks.
