### ISSUE TITLE
This does not even work!

### ISSUE THREAD

**Issue by rh0dium** [docusign/eg-01-python-jwt#4]
This simply does not work as intended..  The SDK this references is not even in alignment with the docs.

**Comment by LarryKlugerDS** [comment]
Hi @rh0dium ,
Please accept my apologies for the problem. The SDK was updated but this example has not yet been updated. Updating this example is planned, but I don't have a schedule date yet from the engineering team. 

I have filed internal bug report DEVDOCS-1362

**Comment by anujism** [comment]
For people who are facing this issue, you can downgrade the `docusign_esign` to 1.0.3. Once the repo is updated, you can go back to updated one.
`pip install docusign-esign==1.0.3`

**Comment by Nickolay-Suslov** [comment]
Any updates here? when we can expect updated examples for v2?

**Comment by LarryKlugerDS** [comment]
Unfortunately I don't have an update at this time. I will ping the responsible team.

**Comment by LarryKlugerDS** [comment]
The team tells me that the planned schedule is 2-3 weeks from today.

**Comment by hffajardo** [comment]
Any update to this example code?  It's now been 3 weeks.

**Comment by baal32** [comment]
What a joke, here we are now 6 weeks from Larry's comment and we're still dealing with broken code samples.  Thanks - you made our decision to switch to adobe sign that much easier.

**Comment by hffajardo** [comment]
> For people who are facing this issue, you can downgrade the `docusign_esign` to 1.0.3. Once the repo is updated, you can go back to updated one.
> `pip install docusign-esign==1.0.3`

FWIW, we downgraded per the comment above and got it working.

**Comment by LarryKlugerDS** [comment]
Hi Everyone,
I've pinged the Examples engineering manager again and have cc'd other managers too. Hopefully the logjam will break up soon. 

I am sorry that this bug has not been fixed. Please accept my apologies for the situation, it is definitely not our goal.

**Comment by LarryKlugerDS** [comment]
The bug fix status was updated to In Progress on Dec 27, 2019.

**Comment by LarryKlugerDS** [comment]
The bug was fixed with the commit https://github.com/docusign/eg-01-python-jwt/commit/e7fe2bd66e8153cc4eb297c82f705e33fa034ac3
